### ISSUE TITLE
onError(), when is it called?

### ISSUE THREAD

**Issue by mirko77** [theogravity/electron-dl-manager#14]
Hi there,

I am not able to catch any HTTP error when starting a download, it just fails silently.

I even tried to provide a wrong URL like 'test', but nothing, am I missing something?

```

 const id = await manager.download({
                        window: mainWindow,
                        url: 'test',
                        saveAsFilename: file.filename,
                        overwrite: false,
                        callbacks: {
                            // item is an instance of Electron.DownloadItem
                            onDownloadStarted: async ({id, item, resolvedFilename}) => {
                                // Send the download id back to the renderer along
                                // with some other data
                                //log.info('Downloading file...');
                                //log.info(id, item, resolvedFilename);
                            },
                            onDownloadProgress: async ({id, item, percentCompleted}) => {
                                // log.info(id, item, percentCompleted);
                            },
                            onDownloadCompleted: async ({id, item}) => {
                                //  log.info(id, item);
                            },
                            onError: (err, data) => {
                                // ... handle any errors
                                log.error('the error is', err, data);
                            }
                        }
                    }
                );

```

**Comment by theogravity** [comment]
See 

https://github.com/theogravity/electron-dl-manager/blob/main/src/CallbackDispatcher.ts

**Comment by mirko77** [comment]
Thanks, no error is thrown. Switched to another library, all good.

**Comment by theogravity** [comment]
> Thanks, but no error is thrown. 
> 
> Switched to another library, all good.

What error are you expecting?

**Comment by theogravity** [comment]
That's because it's not natively treated as an error. Electron's `DownloadItem` doesn't have an explicit `error` event:

https://www.electronjs.org/docs/latest/api/download-item#class-downloaditem

Instead, it treats things like invalid urls as a completed - cancelled event.

```typescript
    const id = await manager.download({
      window: mainWindow,
      url: 'https://invalid-url.com/file.zip',
      saveDialogOptions: {
        title: 'Save File',
      },
      callbacks: {
        onDownloadCancelled: async (data) => {
          console.log('canceled', data)
        },
      }
    });
```

Should it be an error? Yeah, it should. However, the `DownloadItem` doesn't give any hint as to how or why the download was cancelled, so it's hard to tell if it it is an actual error or not. It's why I also provide a flag if the download was cancelled due to user interaction or not.

I'll definitely note this in the readme, but until Electron provides an event for errors on the download item, there's nothing much I can do here.
