### ISSUE TITLE
pause issues

### ISSUE THREAD

**Issue by MrRezai** [theogravity/electron-dl-manager#4]
i use pauseDownload && resumeDownload
but when pause just pause callbacks like download progress and download not pause

when pause : downloaded percent = 3.07 and after 10 sec call resume see 20 percent downloaded

`
ipcMain.on("download", (event, info) => {
    // info.options.onProgress = status => window.webContents.send("download progress", status);
    // download(window, info.url, info.options)
    //   .then(dl => window.webContents.send("download complete", dl.getSavePath()));

    let DownloadID

    DownloadID = manager.download({
      window,
      url: info.url,
      directory: info.options.directory,
      callbacks: {
        onDownloadProgress: async ({ id, item, percentCompleted }) => {
          window.webContents.send('download progress', {
            id,
            percentCompleted,
            bytesReceived: item.getReceivedBytes(),
          });
        },
      }
    })

    ipcMain.on('cancelDownload', () => {
      manager.cancelDownload(DownloadID)
    })

    ipcMain.on('pauseDownload', () => {
      manager.pauseDownload(DownloadID)
    })

    ipcMain.on('resumeDownload', () => {
      manager.resumeDownload(DownloadID)
    })

  });
`

**Comment by theogravity** [comment]
Have you tried debug logging to see if it is actually getting the download item to pause?

Under the hood all it does is just call the download item pause call. I have noticed sometimes where pausing doesn't cause it to stop immediately if you look at my source code for the initiator.

It's possible that this is an Electron-specific bug as all this lib does is call the underlying pause / resume methods on the item.

**Comment by theogravity** [comment]
Here's my test. I'm not able to reproduce, but I do believe you that you are experiencing it. It's hard to know if it's a bug on my side or in electron itself when I can't reproduce the issue:

https://gist.github.com/theogravity/c25fd0250f455ae3a2f6fdee18dd8bb3

I used [`electron fiddle`](https://www.electronjs.org/fiddle) to test

One really far-fetched theory is IPC is taking longer than expected to reach the main process and that's why pause triggering is delayed, but I don't think it'd take so long that you'd see progress after 10s after the pause.

If you can create a fiddle that reproduces the issue, it would really help! You can use the `Load Fiddle` in the toolbar against the URL I provided above to load my fiddle code and adjust the sample.

**Comment by theogravity** [comment]
Another theory is that you're pausing before the internal resume happens:

Non-interactive:
https://github.com/theogravity/electron-dl-manager/blob/main/src/DownloadInitiator.ts#L190

Interactive:
https://github.com/theogravity/electron-dl-manager/blob/main/src/DownloadInitiator.ts#L160

What's going on is I do the following when the user initiates the download:

- Immediately pause
- Set up the listeners / allow the user to select a download location (if using a dialog box)
- Resume the download

I bet what's happening is the user-set pause gets called before the resume.

Let me see if I can address this somehow.

**Comment by theogravity** [comment]
I published 2.4.1

Re-open if you still have the issue.

**Comment by MrRezai** [comment]
thanks,
after download version 2.4.1 my code has error 

![errror](https://github.com/theogravity/electron-dl-manager/assets/151368985/b0dbf663-3b24-442a-84b8-7d873cb7c02d)

**Comment by theogravity** [comment]
Thanks for the report. This was def a situation where unit tests wouldn't have easily discovered the issue. I had to test using a sample app. Found there was a race condition where the `item` actually might not be populated when you call `pauseDownload() / pause()`.

I've published `3.0.0`. The big change is you need to use `await download()` instead of `download()`. This will ensure that the item data is properly populated before you use it against `pauseDownload()`
